version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "5173:5173"
    # depends_on:
    #   - mysql
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    command: php artisan serve --host=0.0.0.0 --port=80

  # mysql:
  #   image: mysql:8
  #   container_name: mysql-laravel
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: laravel
  #   volumes:
  #     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

